// import type { Metadata } from "next";

import { auth } from "@/auth.config";
import { redirect } from "next/navigation";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function ShopLayout({ children }:Readonly<{
  children: React.ReactNode; 
}> ) {

  const session = await auth();

  if ( session?.user ) {
    redirect('/');
  }

  return (
    <main className="flex justify-center">
      <div className="w-full sm:w-[350px] px-10">
      { children }
      </div>
    </main>
  );
}
