// import type { Metadata } from "next";

import { Footer, Sidebar, TopMenu } from "@/components";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function ShopLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <main className="min-h-screen">

      <TopMenu />
      <Sidebar />
      <div className="px-0 sm:px-7">
        { children }
      </div>
      <Footer />
    </main>
  );
}
